# Site settings
title: Kiamehr Personal Page!
description: Kiamehr Personal Page!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kiamehr.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: This is
user_description: PhD Student at Cardiff NLP!
user_title: Kiamehr Rezaee
email: rezaeek@cardiff.ac.uk
twitter_username: kiamehrrezaee
github_username:  kiamehr74
# gplus_username:  lorem_ipsum
# disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
